
keygen: keygen.c
	gcc -g -Wall -std=c99 -o keygen  keygen.c

otp_enc: otp_enc.c
	gcc -g -Wall -std=c99 -o otp_enc otp_enc.c

otp_enc_d: otp_enc_d.c
	gcc -g -Wall -std=c99 -lpthread  -o otp_enc_d otp_enc_d.c


clean:
	rm -f keygen
	
